### ISSUE TITLE
Filtering based on attribute value

### ISSUE THREAD

**Issue by VikramShityalkar** [onury/accesscontrol#12]
I read #8 but I have following scenario, will it be possible to define policy

Resource: Book
Attribute: Publisher
Role: Student
How to define policy for:
-	Allow access if Publisher is XYZ
-	Deny access if Publisher is ABC  

Does accesscontrol support filtering based on attribute value?

**Comment by onury** [comment]
Not in that sense, no.

The principle should be to avoid access-control by a **specific** **record/value** but a resource. 
Otherwise you would need to change/update policy every time you add a new publisher.

So, this is a design issue rather than how AC handles it. 
In your case, I'd define two resources: `BookGroup1`, `BookGroup2`

(In your backend, you'd still fetch these resources by filtering by their publishers.)

```js
// grants for students
ac.grant('Student').readAny('BookGroup1');
// grants for teachers
ac.grant('Teacher').extend('Student').readAny('BookGroup2'); 

// check student permissions
ac.can('Student').readAny('BooksGroup1').granted   // —> true
ac.can('Student').readAny('BooksGroup2').granted   // —> false

// check teacher permissions
ac.can('Teacher').readAny('BooksGroup1').granted   // —> true
ac.can('Teacher').readAny('BooksGroup2').granted   // —> true
```

Also see [this F.A.Q.](https://github.com/onury/accesscontrol/blob/master/FAQ.md#what-is-a-resource)
