### ISSUE TITLE
UI widget to manage roles, resources and permissions

### ISSUE THREAD

**Issue by amit777** [onury/accesscontrol#29]
I was wondering if there are some example front end widgets or suggestions of rules of components that work well for end users to define and manage permissions, resources and role. Any guidance on best practices or tools to get started would be highly appreciated!

**Comment by onury** [comment]
This is mainly a low-level server side library. No front-end UI is provided.

How you'd implement a management UI is up to your application design. AccessControl is not coupled with any kind of frontend or backend systems/frameworks. It can work with all. There are lots of ways, UI frameworks you could use. How and where you'll persist the AC data is another subject.

So it's hard to give you examples or best practices. All I can say is; since this is security-related, make sure you correctly authenticate the managing users.
