### ISSUE TITLE
Client Side Filter

### ISSUE THREAD

**Issue by CodeCorrupt** [onury/accesscontrol#31]
I'm in a situation where I have the security enforced server side, but I'd like to be able to pass a user's grants down to the client to alter the way the page renders. 

Could we add a method to export grants in a way that can be consumed client side or create a client module that can read from an exported object and use it?

Edit: upon reading more I see this uses the 'notation' module which can be used client side for a specific attribute list. however It would be useful to have the ability to export a json object of all permissions and attributes granted to a specific user. I created a very crude one below of what I'm thinking.

```
let role = '<your role>'
let grants = {};

// Add grants to the u object
for (let verb of ['create', 'read', 'update', 'delete']) {
  for (let possession of ['Own', 'Any']) {
    grants[verb + possession] = {};
    for (let resource of ac.getResources()) {
      let permission = ac.can(role)[verb + possession](resource);
      if (permission.granted) {
        grants[verb + possession][resource] = permission.attributes;
      }
    }
  }
}
```

**Comment by scandinave** [comment]
I think this answer your question : [https://onury.io/accesscontrol/?api=ac#AccessControl#getGrants](https://onury.io/accesscontrol/?api=ac#AccessControl#getGrants)

**Comment by CodeCorrupt** [comment]
That's perfect. Thank you. Not sure how I missed that there was full API documentation.

**Comment by onury** [comment]
First, I don't recommend passing the grants model to client side for security reasons.
And second, the grants model object is not suitable as is, for this use case anyway. Especially if there are extended roles in your grants object.

Remember that in AccessControl, inheritance is done by reference.
```js
ac.grant('user').read('profile', ['*', '!id'])
   .grant('admin').extend('user');

console.log(ac.getGrants()); // will output:

{
    "admin": {
        "$extend": ["user"]
    },
    "user": {
        "profile": {
            "read:any": ["*", "!id"]
        }
    }
}
```
You see, `admin` role does not have the `profile` resource explicitly defined on the model. So something like your example function will not truly work here. It's a bit more complex actually.

Anyway, don't expose your grants model directly on the client side.
Why don't you; 
- Use the permission object before returning your responses in your API. 
 i.e. `.filter()` method before returning your resource representation/object.
- Conditionally render by attribute existence. 

## On Server-Side
```js
const permission = ac.can(role).read('profile');
if (permission.granted) {
    const data = getSomeProfile();
    const filteredData = permission.filter(data);
    response.json(filteredData);
} else {
    response.status(403).end(); // forbidden
}
```

## On Client-Side

We'll redirect to another section if we get a forbidden response.
Otherwise, we'll show the view but only with the attributes we've got from the response (which was filtered by AccessControl before sent to us).

Some controller:
```js
const result = requestSomeProfile();
if (result.forbidden) return redirect('/');
bindToProfileView(result);
```
Some view:
```html
{?profile.id}  <!-- conditional: checking for existence of id attribute -->
    ID: <b>{profile.id}</b>  <!-- render only if we have an id attribute -->
{/profile.id}

```

**Comment by scandinave** [comment]
Interesting. The doc does not say something on the extend in the grant object. I was thinking that permission was just copy to the child role when the declaration happen. Is there something similar for deny permission or it's purely a remove of the permission.
I mean something like this :

`{
    "admin": {
        "$extend": ["user"]
        "profile": {
            "read:any": ["*", "!id"]
        }
    },
    "user": {
        "profile": {
            "DenyRead:any": ["*", "!id"]
        }
    }
}`

Where the user role extends admin role and deny a previously grant permission.

**Comment by CodeCorrupt** [comment]
@onury Thanks for the quick, in depth reply.
The role may have read access, just not update so I want to grey out the input box so they can see, but not edit. I think you're right about doing it server side. I could use the `filter` on a copy of the object server side then pass the list of keys down and use that list of permitted keys.

**Comment by onury** [comment]
@scandinave Docs indicate that inheritance is [done by reference](https://github.com/onury/accesscontrol#roles). This internally helps maintaining the grants model more efficiently. Imagine you have `roleA` extending `roleB` extending `roleC` extending 3 more roles... By the time you extend `roleZ`, you'll have to re-write the grants for each and every role up the tree.

Denying a permission is (currently) just a convenience feature. If you don't grant anything, you don't need to explicitly deny. What `.deny()` does is, set an empty array `[]` for the permitted attributes. So when extended and since it's only referenced, AC will use whatever the current attributes are when checking for permissions.

> `{ "admin": { "$extend": ["user"], "profile": { "read:any": ["*", "!id"] } }, "user": { "profile": { "DenyRead:any": ["*", "!id"] } } }`

would be:

```js
{
	"admin": {
		"$extend": ["user"],
		"profile": {
			"read:any": ["*", "!id"]
		}
	},
	"user": {
		"profile": {
			"read:any": []
		}
	}
}
```
And when checked for permission, attributes are "optimistically union'ed" — meaning more privileges will win over less. In this case; `["*", "!id"] UNION [ ]` ⇒ `["*", "!id"]` because `["*", "!id"]` is explicitly defined for the `admin` role.

**Comment by scandinave** [comment]
Ok thanks you for the explanation. Really instructive. Why not make the child permissions take predominance over the parent one?

**Comment by onury** [comment]
How do you mean?

**Comment by onury** [comment]
> I could use the `filter` on a copy of the object server side then pass the list of keys down and use that list of permitted keys.

@CodeCorrupt that's ok to do in most cases.
Just `Object.keys(permission.filter(data))` and return.

**Comment by scandinave** [comment]
I mean, In the previous example, with predominance of the child permissions, i can selectively drop/add one or more permissions over the parent role. That allow making  one role with all common permissions and just change the needed permissions in the children roles. 
So if common permissions changes, it's easy  to update them for all  ofchildren roles.

**Comment by onury** [comment]
@CodeCorrupt  sorry I think you also need the keys that are not permitted.
> I could use the `filter` on a copy of the object server side then pass the list of keys down and use that list of permitted keys.

```js
const allKeys = Object.keys(data);
const data = permission.filter(result);
response.json({
    allKeys,
    data
});
```
If this is the case, just make sure keys are not "implying" anything sensitive.

**Comment by onury** [comment]
@scandinave inheritance direction is down the tree but updating should be done upwards.

And A) that would still slow down performance and B) actually, there may not be any common permissions. You may grant the same resource `x` for both roles `a` and `b` but with different resource-attributes. 

And in future, I'll introduce more features that may/will make each grant even more unique.

**Comment by scandinave** [comment]
Ok thanks you for your patience. You make a great job.

**Comment by onury** [comment]
No problem at all. Glad to help.
