### ISSUE TITLE
custom actions and user-based access control

### ISSUE THREAD

**Issue by awHamer** [onury/accesscontrol#38]
Hi, @onury!
First of all  thank you for such a great lib with a clear api!

I have a several questions:
- How can I control access to features which are build on top of my resources.
It's very clear for me about classic CRUD, but I have a lot of extra features/action which role can do with a resource such as: `export` resources,  `import` resources, `bulk update` resources, `comment` etc. For example: Admin can view any `resource`, `bulk edit resource`, `export resource` into csv and `comment` on `resource`. But user can only `view any resource`

- It is possible to control access to a particular resources? I know that Policies in ABAC can do this trick, specify something like: 
```javascript 
{"own": ["resource.creator_id=user.id"], "sharedToMe": ["resource.id in (sharedIds)"] }
```

Thank you!

**Comment by onury** [comment]
Hi @awHamer, thanks.

About your first question... AccessControl defines actions by CRUD operations. See [this in FAQ](https://github.com/onury/accesscontrol/blob/master/docs/FAQ.md#what-is-an-action) for more info.

Your action examples are either covered by CRUD or some of them are actually resources rather than an action. Let's see:
- **`export` a resource**: Here the resource is the original source and what you export would typically be a cloned, copied or transformed object - which is actually a different resource. Let me put it this way; do you consider the original and exported the same thing? For example, it could be a database row (let's say an invoice record), exported to a PDF file. You could do this: 
```js
ac.grant('accountant').createAny('invoice')
  .grant('user').createOwn('pdf-invoice');
```
- **`bulk-edit` a resource**: Here the action can still be defined as an update. For now, if you need distinguished control over bulk vs single updates; you can define a two resources in AC. 
```js
ac.grant(role).update('video')
  .grant(role).update('video-collection');
```
 _(Note that indicating "bulk" as a context attribute can be done in the upcoming major release when contexts are introduced.)_
- **`comment` on a resource**: For example, comment on a video. Video is a resource. So is a comment, right. You probably have two different storages (e.g. db table) for each. So how about: `ac.grant(role).create('comment')` ?

You see you can always get away with CRUD actions. IMO, this keeps it simpler and meaningful. But if we see a true need to define custom actions or AC users find it useful enough; I can consider implementing this.

About your second question, that implementation seems a bit coupled with data models but v3 will have [similar API](https://github.com/onury/accesscontrol/issues/24#issuecomment-344465678) with "contexts".

**Comment by awHamer** [comment]
Thanks for the clear answer, actually you are right about `export`, `bulk` these are also CRUD and can be fit in my requirements. Am I right understand that I can make resources like this
```javascript
ac.grant(role).create('comment-user').updateOwn('comment-user')
```
which means that I want to grant a role ability to comment only on user resource?

 or

Is it will not looks strange if I grant access to a particular resource record the way like this:

```javascript
ac.grant(role).view('location-111')
```

Where `location` is resource, 111 is `location` id?
Thanks.

**Comment by onury** [comment]
Starting with your last question; you **never** control access by a **specific user**. The subject should always be a **role**. Otherwise, in its simplest form, you'll have to deal with updating the code every time that specific user has some changes. And you since you cannot do this for each and every user; that's no way to maintain the code or manage access control.

> can make resources like this: `ac.grant(role).create('comment-user').updateOwn('comment-user')`

I suggested `ac.grant(role).create('comment')`. You should generally avoid implying a role within a resource name and vice-versa. If what you mean is some role can comment on (for example) a user video, you could do `ac.grant(role).create('video-comment')`.

> `ac.grant(role).read('location-111')`  Where location is resource, 111 is location id?

No, never! Do not mix a resource name and an attribute like that. I don't even get what the purpose here is.

**Comment by awHamer** [comment]
> you never control access by a specific user. The subject should always be a role. Otherwise, in its simplest form, you'll have to deal with updating the code every time that specific user has some changes

I didn't meant to control it in hard-coded way :)
>  You should generally avoid implying a role within a resource name and vice-versa

That's **True**, didn't get where I propose it :)

> If what you mean is some role can comment on (for example) a user video, you could do `ac.grant(role).create('video-comment')`.

Exactly what I meant.

>No, never! Do not mix a resource name and an attribute like that. I don't even get what the purpose here is.

But I need to control access some users to a some resource items as well...
For example there is role `user`, it has no access to resource `asset` at all.
The role `admin` may have ability to **SHARE** (_with specify what fields user can read, what fields user can write, can user delete or not etc_) particular asset to some **User**, and so User's role must not be changed, he still should not see any assets, except shared. 
That's why I'm asking about it.

**Comment by onury** [comment]
Ok. There is nothing wrong with what you want to achieve. But it requires **user-based** access control (at individual level) which is out of scope of AccessControl.js (at least currently but no plans). This is still doable but AC cannot be the whole solution here. 

In a design like this; these privileges you indicate actually become a resource themselves. So, you should design this kind of thing with AC and your app-logic, **in combination**.

### Design Example

Below is a quick example of how I'd design this kind of structure.  
- Define 3 resources: `asset`, `shared-asset` and `asset-privileges`.
- Each resource will have a (route) endpoint for each defined action.
- Create 2 corresponding database tables: `assets` and `assetPrivileges`.
- Assuming we also have a `users` table.

#### Resource: `asset`
- This resource explicitly represents the database table: `assets`
- Attributes: `id`, `name`, `type`, `price`, `date`  
- AC Rule: Only `admin` role can c/r/u/d any asset.
```js
ac.grant('admin')
  .create('asset')
  .read('asset')
  .update('asset')
  .delete('asset');
```

#### Resource: `shared-asset`
- This resource implicitly defines "assets" that some specific user (records) have privileges to.
- This resource is not represented by a database table. But it's related with the `assets` resource. (i.e. a sub-group of assets).
- AC Rule: None. Because this requires handling by individual users, instead of roles. This will be handled within the app routes, rather than AC.

#### Resource: `asset-privileges`
- This resource defines the shared asset privileges that a user (record) has. 
- This resource explicitly represents the **relational** database table: `assetPrivileges`
- Attributes:
  -  `userId` (int, foreign-key: `users.id`)
  -  `assetId` (int, foreign-key: `assets.id`)
  -  `canDelete` (boolean)
  -  `readables` (string, a list of readable `asset` attributes)
  -  `writables` (string, a list of writable `asset` attributes)
- AC Rule: `admin` role can c/r/u/d any `asset-privileges` resource, with all attributes:
```js
ac.grant('admin')
  .create('asset-privileges')
  .read('asset-privileges')
  .update('asset-privileges')
  .delete('asset-privileges');
```

### App Routes
_Note: I'm not minding the AC resource "possession" (own or any) here since there is no concept of assets ownership in that sense, in the app-design._

#### Creating asset privileges
```js
app.post('/asset-privileges', (req, res) => {
    const data = req.body;
    const permission = ac.can(req.user.role).create('asset-privileges');
    if (permission.granted) {
      const result = await db.createAssetPrivileges(data);
      res.json(result);
    } else {
      res.status(403).end();
    }
});
```
You can implement similar middlewares for:
- create: `app.post('/asset-privileges', handler)`
- read: `app.get('/asset-privileges/:id', handler)`
- update: `app.put('/asset-privileges/:id', handler)`

#### Deleting assets
```js
app.delete('/assets/:id', (req, res) => {
    const assetId = Number(req.params.id);
    const permission = ac.can(req.user.role).delete('asset');
    if (permission.granted) {
      const result = await db.deleteAsset(assetId);
      res.json(result);
    } else {
      res.status(403).end();
    }
});
```
You can implement similar middlewares for:
- create: `app.post('/assets', handler)`
- read: `app.get('/assets/:id', handler)`
- update: `app.put('/assets/:id', handler)`

#### Updating "shared" assets
```js
app.update('/shared-assets/:assetId', (req, res) => {
    const assetId = Number(req.params.id);
    const data = req.body;
    const userId = req.user.id;
    const privileges = await db.getAssetPrivilegesByUser(userId, assetId);
    if (privileges && privileges.writables) {
      // making use of the static .filter() method of AccessControl class.
      // This is similar to Permission#filter method.
      const filteredData = AccessControl.filter(data, privileges.writables);
      const result = await db.updateAsset(assetId, filteredData);
      res.json(result);
    } else {
      res.status(403).end();
    }
});
```
You can implement similar middlewares for:
- read: `app.get('/shared-assets/:assetId', handler)`
- update: `app.put('/shared-assets/:assetId', handler)`
- There is no "create" endpoint for `shared-assets`.   
Assets can be created via `app.post('/assets', handler)` by `admin` roles.

#### Deleting "shared" assets
```js
app.delete('/shared-assets/:assetId', (req, res) => {
    const assetId = Number(req.params.id);
    const userId = req.user.id;
    const privileges = await db.getAssetPrivilegesByUser(userId, assetId);
    if (privileges && privileges.canDelete) {
      const result = await db.deleteAsset(assetId);
      res.json(result);
    } else {
      res.status(403).end();
    }
});
```
_Note: This approach is for demonstration. Depending on the design; we could also delete a shared asset with a single SQL query by probably joining `assets`, `users` and relational `assetPrivileges` tables._
