### ISSUE TITLE
What about true resource check (maybe with groups)

### ISSUE THREAD

**Issue by cyrilchapon** [onury/accesscontrol#9]
In here we have a use case that is hard to cover (and in fact uncovered by any library) :
Instead of simply checking permissions against a role and a "resource" (which, in fact, is a more resource**Type**), we are trying to authorize against a role and a true resource (a resource unique instance), going through groups of resources.

The library, which is very great and has a clean and robust API, offers what I just called "role against resourceType", by granting/revoking one role to/from *any* instance of the resourceType, or *own* instance of resourceType.

What about a strategy that would allow to grant a role to *that specific* resource, or maybe simpler *any resource in that group* ?

that could lead to something like
```
var ac = new AccessControl();
ac.grant('user')
    .createOwn('video')
    .deleteOwn('video')
    .readGroup('video', 'group1') // <== HERE
  .grant('admin')
    .extend('user')
    .updateAny('video', ['title'])
    .deleteAny('video');

var permission = ac.can('user').createOwn('video');
console.log(permission.granted);    // —> true
console.log(permission.attributes); // —> ['*'] (all attributes)

permission = ac.can('admin').updateAny('video');
console.log(permission.granted);    // —> true
console.log(permission.attributes); // —> ['title']

var permission = ac.can('user').readGroup('video', 'group1');
console.log(permission.granted);    // —> true
console.log(permission.attributes); // —> ['*'] (all attributes)
```

there seem to be more than a need on this feature. See :
https://github.com/OptimalBits/node_acl/issues/241
https://github.com/OptimalBits/node_acl/issues/243

**Comment by onury** [comment]
I need to understand what you gain by grouping resources, in your case. 

What you call "a group of a resource" or a "resource type" is essentially just another resource, if it needs to be distinguished from others.

You're defining a `video` resource and a group of video items (records) as `group1`. Wouldn't it work if instead you define simpler and more specific resources such as:

```js
ac.grant('admin')
    .readAny('videoGroup1')
    .readAny('videoGroup2')
    // so on ...
```

Or are you talking about grouping unrelated resources such as `group1` would include resources `video` and `photo` for example?

**Comment by cyrilchapon** [comment]
Hey @onury thanks for replying.

> Or are you talking about grouping unrelated resources such as group1 would include resources video and photo for example?
Well more like the second case.

> ac.grant('admin')
>     .readAny('videoGroup1')
>     .readAny('videoGroup2')
>     // so on ...
I think it could work but it would be strange to mix a *resourceType* concept with a *resourceInstance* concept, wouldn't it ?

**Comment by onury** [comment]
Well, actually grouping should mean aliasing multiple resources with another name. Specifically, `group1` would consists of **the** `video` and `photo` resources. Not a sub-list of video/photo resource instances. Otherwise, it's against the concept this library implements.

AccessControl has no knowledge about individual instances or users; it implements RBAC with implicit access control. An implicit access control only works with your (the developer's) code and decisions.

When you bring *instance* to this concept, it's not really meaningful. An instance is dynamic (it may exists, then it may not). But a resource is a definition; it's always there, static. For example, even if you have no videos (instances) yet, you can have a logical video resource that has all the semantics to manage/restrict the resource.

Same for users vs roles. Don't confuse RBAC for applications with SQL implementations of ACL or file-system ACL. You should never involve individual users/objects in this.

Think of it this way; if we were to authorize access to a resource by individual users; then we'd have to update the code every time a new user is added or deleted; or grants are changed for that user. In other words, you shouldn't need to touch the source code when policies/privileges change.

In v2, I'll introduce **scopes** which will bring finer granularity. You will be able to switch between remaining implicit (as is) or a bit more explicit. 

I cannot give you a code example since the API is not finalized yet but for example, scopes will allow you to restrict access based on date and time. Or it will allow you to add tags to a grant. These tags would be only meaningful to you/your application. For example a DELETE action will mean a permanent delete app-wise but if a grant is tagged with `soft` it would mean an UPDATE.

Maybe you can take advantage of scopes for your use case. You'd have a better understanding once v2 is released. For now, I'll leave it at this..
